+incdir+$ROOT_PATH/rtl

-sverilog
$ROOT_PATH/rtl/UNITY_DECODER.sv
$ROOT_PATH/rtl/GFMULT.sv
$ROOT_PATH/rtl/GFEXP.sv
$ROOT_PATH/rtl/GFDIV.sv
$ROOT_PATH/rtl/SYNDROME_GENERATOR.sv
$ROOT_PATH/rtl/SSE_CORRECTOR.sv
$ROOT_PATH/rtl/DE_CORRECTOR.sv
$ROOT_PATH/rtl/DECISION.sv
$ROOT_PATH/rtl/ERROR_LOCATION.sv