CC=g++
CFLAGS=-O2
EXEC=Reliability_Against_Raw_BER_sim_start

all: $(EXEC)

$(EXEC): Reliability_Against_Raw_BER_sim.cpp
	$(CC) $(CFLAGS) Reliability_Against_Raw_BER_sim.cpp -o $(EXEC)

clean:
	rm -f $(EXEC)

